### ISSUE TITLE
test_manual_no_input can work!

### ISSUE THREAD

**Issue by yshavit** [dogboydog/manual-workflow-test#2]
I stumbled on your repo while wondering the same thing. :-)

You have this in `test_manual_no_input.yaml`, which didn't work for me (and I don't see any runs here, so I'm guessing it didn't work for you, either):

```
on:
  workflow_dispatch: 
```

But it does work if you explicitly provide an empty map:

```
on:
  workflow_dispatch:  #{}
```

**Comment by dogboydog** [comment]
Nice thanks. I'll change it here in case anyone else needs an example

**Comment by dogboydog** [comment]
Hey actually it seems like it works as written. I thought I had trouble with it but it seems okay now
https://github.com/dogboydog/manual-workflow-test/actions/runs/203247672

**Comment by yshavit** [comment]
Oh, huh, look at that! Nice.
